### ISSUE TITLE
Delete route doesn't delete it in the db

### ISSUE THREAD

**Issue by pedroponte** [apioo/fusio-impl#21]
When deleting a route via the UI, it doesn't get deleted from the db.
I believe the problem was that there was a fk contraint check that prevented it form deleting child records.
I have changed my db but think this should be fixed in a future release.
Thanks

**Comment by chriskapp** [comment]
Hey, this currently also an intentional choice since if you delete a route we only set a flag that the route is deleted and we dont actually delete the record. We do this since our changelog etc. depends on the id and you can also easily restore the record if you have made a mistake.

**Comment by pedroponte** [comment]
I see..
However, it would be nice to be able to force delete them from UI, even if from an archived filtered view.
If I need to rename routes or actions, I can't, so the only way is to delete them and create new ones. 
If for some reason I want to use the same name then I get a conflict.
Thanks

**Comment by chriskapp** [comment]
At the latest Fusio version there is a trash panel s.
![image](https://github.com/apioo/fusio-impl/assets/2505846/331efe10-a593-4593-a837-ca92fa0900d0)
where a user can see all deleted records and there is also a way to restore a record.
