### ISSUE TITLE
Make logs optional for specific routes

### ISSUE THREAD

**Issue by pedroponte** [apioo/fusio-impl#22]
+1 to disable logging on specific routes or actions.

Currently using react where the suggested approach is to use bcrypt :

 1. password is saved as a hash in db.
 2. the same password never generates the same hash
 3. client for auth sends pass in clear text via ssl and bcrypt validates the clear password against the hash.

Seems that this is the standard option so that a hash to hash comparison is avoided as it is not a safe method.

However, that will mean the password will be shown in clear text in the logs..

Also, the fact that the logs are not rotated seems to me a problem awaiting to explode at some point due to storage, performance etc..

More details here:
https://dev.to/silvenleaf/password-hashing-with-bcrypt-easiest-explanation-5gpg

**Comment by chriskapp** [comment]
Hi, if I understand you correctly, your use-case is here that the request logs contains sensitive data and you dont want that those data is stored at the logs? In general I would of course recommend to not send any sensitive data as plaintext. But in general disable logging for a route would be possible, but then the dashboard and all analytics panels are not working for this route.

**Comment by pedroponte** [comment]
Thank you.

Is is possible to use other PHP functions such as openssl_decrypt in php worker or sandbox?
What and how would I import that into the php file? 
I have already enabled it in my php.ini  but can't seem to save the file due to server error when incovking that function.
TIA

**Comment by chriskapp** [comment]
Hey, so regarding the question if you use the PHP Sandbox action we use a Sandbox s. https://github.com/apioo/psx-sandbox/blob/master/src/SecurityManager.php#L34 to execute only specific functions which are available in the whitelist, if you need specific function please create a PR at the package. In general if you have more complex code it is recommended to create a dedicated class.
