### ISSUE TITLE
Rotate logs to improve performance and reduce storage

### ISSUE THREAD

**Issue by pedroponte** [apioo/fusio-impl#23]
Can you please look into an option to rotate logs and cler them up after a specific configurable setting to reduce storage usage and improve performance? 
TIA

**Comment by chriskapp** [comment]
Hi, so we have already a command which you can call to rotate your logs s. 
`php ./bin/fusio system:log_rotate`
so you can simply setup a cron which executes this command, see also https://github.com/apioo/fusio/issues/420

**Comment by pedroponte** [comment]
Thanks.
Can you give an example of how to create a class with this command so I can then invoke it in the cron tasks?
TIA

**Comment by chriskapp** [comment]
so this is not an action which you can invoke via a route, it is a simple command which you can invoke through the CLI. Since this is an maintenance task you most like like dont want to call such an action via route. So you can simply execute the command like described above in your terminal.
