### ISSUE TITLE
Alert message points to incorrect file for config changes {configuration.php} [scratched head at 3am]

### ISSUE THREAD

**Issue by Cale-Torino** [apioo/fusio-impl#28]
Hi, just letting you know that in the latest version [`3.1.1` at this time] , the Alert message shown when a user has not enabled the `market_place` or `php_sandbox` etc. says to change the setting in the `configuration.php` file however those settings must be changed in the `.env` file in the root directory. 

I was searching everywhere for the proper `configuration.php` file and eventually found out that it's the .env file.

Also I installed via the web installer method.

Hopefully this helps save time incase som1 has the same issue.

cheers

![Screenshot 2022-07-11 183414](https://user-images.githubusercontent.com/52330180/178316740-0e98417a-d165-4490-9618-af5bb32de0b3.jpg)

![Screenshot 2022-07-11 183611](https://user-images.githubusercontent.com/52330180/178316761-b290f003-dcfe-4848-a9b5-2c59e39cd8c4.jpg)

**Comment by chriskapp** [comment]
Hey,  we have added a "marketplace" page at our documentation s. https://docs.fusio-project.org/docs/concepts/marketplace which should help to explain this setting.
