### ISSUE TITLE
GET Url can't be longer than 255 character

### ISSUE THREAD

**Issue by subangkit** [apioo/fusio-impl#3]
I'm love fusio API management.

{
    "success": false,
    "title": "Doctrine\\DBAL\\Exception\\DriverException",
    "message": "An exception occurred while executing 'INSERT INTO fusio_log (routeId, appId, userId, ip, userAgent, method, path, header, body, date) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"66\", null, null, \"192.168.8.1\", \"Mozilla\\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\\/537.36 (KHTML, like Gecko) Chrome\\\/58.0.3029.110 Safari\\\/537.36\", \"GET\", \"\\\/xxxxx?filter=%5B%22%5B%5C%22codefication%5C%22,%5C%22contains%5C%22,%5C%22Te%5C%22%5D%22,%22and%22,%5B%5B%22DK%22,%22%3D%22,%22D%22%5D,%22or%22,%5B%22DK%22,%22%3D%22,%22K%22%5D%5D%5D&sort=%7B%22selector%22:%22DK%22,%22desc%22:false,%22isExpanded%22:true%7D&userData=%7B%7D\", \"Authorization: \\nHost: fusio.apotek.com\\nConnection: keep-alive\\nCache-Control: max-age=0\\nUpgrade-Insecure-Requests: 1\\nUser-Agent: Mozilla\\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\\/537.36 (KHTML, like Gecko) Chrome\\\/58.0.3029.110 Safari\\\/537.36\\nAccept: text\\\/html,application\\\/xhtml+xml,application\\\/xml;q=0.9,image\\\/webp,*\\\/*;q=0.8\\nAccept-Encoding: gzip, deflate, sdch\\nAccept-Language: en-US,en;q=0.8,id;q=0.6\\nCookie: gvc=918vr2431394544826301\", null, \"2017-06-07 21:29:36\"]:\n\nSQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'path' at row 1 in \/var\/www\/fusio.apotek.com\/vendor\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php on line 115",
    "trace": "#0 \/var\/www\/fusio.apotek.com\/vendor\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(128): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \/var\/www\/fusio.apotek.com\/vendor\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(1015): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'INSERT INTO fus...', Array)\n#2 \/var\/www\/fusio.apotek.com\/vendor\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(714): Doctrine\\DBAL\\Connection->executeUpdate('INSERT INTO fus...', Array, Array)\n#3 \/var\/www\/fusio.apotek.com\/vendor\/fusio\/impl\/src\/Logger.php(73): Doctrine\\DBAL\\Connection->insert('fusio_log', Array)\n#4 \/var\/www\/fusio.apotek.com\/vendor\/fusio\/impl\/src\/Controller\/SchemaApiController.php(152): Fusio\\Impl\\Logger->log('66', NULL, NULL, '192.168.8.1', Object(PSX\\Http\\Request))\n#5 \/var\/www\/fusio.apotek.com\/vendor\/psx\/framework\/src\/Filter\/ControllerExecutor.php(48): Fusio\\Impl\\Controller\\SchemaApiController->onLoad()\n#6 \/var\/www\/fusio.apotek.com\/vendor\/psx\/framework\/src\/Filter\/FilterChain.php(79): PSX\\Framework\\Filter\\ControllerExecutor->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Framework\\Filter\\FilterChain))\n#7 \/var\/www\/fusio.apotek.com\/vendor\/psx\/framework\/src\/Filter\/UserAgentEnforcer.php(41): PSX\\Framework\\Filter\\FilterChain->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#8 \/var\/www\/fusio.apotek.com\/vendor\/psx\/framework\/src\/Filter\/FilterChain.php(79): PSX\\Framework\\Filter\\UserAgentEnforcer->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Framework\\Filter\\FilterChain))\n#9 \/var\/www\/fusio.apotek.com\/vendor\/psx\/framework\/src\/Loader\/Loader.php(158): PSX\\Framework\\Filter\\FilterChain->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#10 \/var\/www\/fusio.apotek.com\/vendor\/psx\/framework\/src\/Loader\/Loader.php(126): PSX\\Framework\\Loader\\Loader->executeController(Object(Fusio\\Impl\\Controller\\SchemaApiController), Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#11 \/var\/www\/fusio.apotek.com\/vendor\/psx\/framework\/src\/Dispatch\/Dispatch.php(120): PSX\\Framework\\Loader\\Loader->load(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Framework\\Loader\\Context))\n#12 \/var\/www\/fusio.apotek.com\/public\/index.php(30): PSX\\Framework\\Dispatch\\Dispatch->route(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#13 {main}",
    "context": "111             case '1566':\n112                 return new Exception\\NotNullConstraintViolationException($message, $exception);\n113         }\n114 \n<b>115         return new Exception\\DriverException($message, $exception);\n<\/b>116     }\n117 \n118     \/**\n119      * {@inheritdoc}\n"
}

**Comment by k42b3** [comment]
Hi, ok we should probably increase the size of the logging column. 255 characters is indeed a little short I think 1024 should be enough. If the url is longer we should truncate the rest.

**Comment by k42b3** [comment]
We have increased the log column in the following commit 56b71bb8aedff330bb0baa9d5164d6ee6ce91c3b which is then included in the next release. So this should fix the problem in the future.

**Comment by subangkit** [comment]
Thanks for update, no longer error with fusio 0.9.0
