### ISSUE TITLE
Allow PATCH method

### ISSUE THREAD

**Issue by christoph-bessei** [apioo/fusio-impl#4]
I would like to implement a REST API which follows the [JSON API](http://jsonapi.org/) standard.
Because of this I need the PATCH method for some requests, but PATCH is currently not allowed by fusio. Is there a reason for this? I added "PATCH" at the following locations and it seems to work fine now:
1. Add a doPatch (just calls executeAction, like doPost) method to [SchemaApiController](https://github.com/apioo/fusio-impl/blob/2e4975169eba55e40bf63f82512ef1dd33a0866d/src/Controller/SchemaApiController.php#L223)
2. Add PATCH to [Transformer/Routes.php](https://github.com/apioo/fusio-impl/blob/2e4975169eba55e40bf63f82512ef1dd33a0866d/src/Service/System/Deploy/Transformer/Routes.php#L78)
3. Add PATCH to [Routes/Config.php](https://github.com/apioo/fusio-impl/blob/2e4975169eba55e40bf63f82512ef1dd33a0866d/src/Service/Routes/Config.php#L104)
4. Add PATCH to [Schema/Routes.php](https://github.com/apioo/fusio-impl/blob/2e4975169eba55e40bf63f82512ef1dd33a0866d/src/Backend/Schema/Routes.php#L39)

**Comment by k42b3** [comment]
Hi, sounds great. So there is currently no specific reason, basically we have implemented only the methods from the HTTP RFC but as PATCH is more used I think this would be a good addition.

If you like you could create a pull request to the places which you have mentioned. But there are probably also some other tasks which we need todo:

 - The table `fusio_routes` has a methods column which contains all available methods, [there](https://github.com/apioo/fusio-impl/blob/master/src/Service/Routes.php#L98) we would need to add the PATCH method.
 - The table `fusio_scope_routes` has also a methods column which contains all methods which are allowed for the scope. This comes from the backend [create](https://github.com/apioo/fusio-backend/blob/master/app/controller/scope/create.html#L40) and update scope dialog.
 - At the backend app we would also need to add the PATCH method at the route [create](https://github.com/apioo/fusio-backend/blob/master/app/controller/routes/create.js#L10) and update dialog.

So these are the topics from the top of my head. But feel free to create a PR only with the places which you have mentioned. I would then add those also to the backend app and probably add also some test cases.

**Comment by k42b3** [comment]
The PR was merged and the PATCH method will be supported in the next release.
