### ISSUE TITLE
InnoDB instead of MyISAM

### ISSUE THREAD

**Issue by riwin** [apioo/fusio-impl#6]
https://github.com/apioo/fusio-impl/blob/fbbdabbc80907cf1bc93369e1f0b78c68231e26f/src/Database/Version/Version307.php#L197

Ar there any known issues if i am using InnoDB instead? I'm forced to use only InnoDB. MyISAM is not supported by my hoster.

**Comment by chriskapp** [comment]
Hi, this should be no problem, we have only used MyISAM on some tables since it is a bit faster for inserts but you can also use InnoDB on all tables.
